name: Secure Deployment

on: [push]

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      ENCRYPTION_KEY: ${{ secrets.ENCRYPTION_KEY }}
    
    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Check for .env.enc
      run: |
        if [ ! -f "meme_tracker/config/.env.enc" ]; then
          echo "::warning::加密文件meme_tracker/config/.env.enc不存在，将使用默认配置"
          touch meme_tracker/config/.env
          echo "REDDIT_CLIENT_ID=default" >> meme_tracker/config/.env
          echo "REDDIT_CLIENT_SECRET=default" >> meme_tracker/config/.env
        fi

    - name: Decrypt environment
      run: |
        python -c "
        import sys
        from cryptography.fernet import Fernet
        try:
          cipher = Fernet(b'${{ env.ENCRYPTION_KEY }}')
          with open('meme_tracker/config/.env.enc', 'rb') as f:
            with open('meme_tracker/config/.env', 'wb') as out:
              out.write(cipher.decrypt(f.read()))
        except Exception as e:
          print(f'::error::解密失败: {e}')
          sys.exit(1)
        "

    - name: Security audit
      run: |
        python meme_tracker/tools/security_audit.py || echo "::warning::安全审计发现问题但继续执行"

    - name: Install dependencies
      run: |
        pip install -r requirements.txt
        pip install cryptography

    # 添加您的部署步骤...