name: Security Audit (New)
on:
  schedule:
    - cron: "0 0 1 * *"
  workflow_dispatch:

jobs:
  security-scan:
    runs-on: ubuntu-latest
    steps:
      - name: Verify Action Versions
        run: |
          echo "确保所有actions使用最新版本"
          echo "当前环境已禁用v3 actions"
          
      - uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
          
      - name: Cache dependencies
        uses: actions/cache@v3
        with:
          path: |
            ~/.cache/pip
            .pip-cache
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          
      - name: Install tools
        run: |
          pip install --upgrade pip
          pip install safety bandit
          
      - name: Run Security Scans
        run: |
          safety check --full-report
          bandit -r . -f html -o report.html
          
      - name: Upload Report
        uses: actions/upload-artifact@v4
        with:
          name: security-report
          path: report.html