name: Security Audit
on:
  schedule:
    - cron: '0 0 1 * *' # 每月1日执行
jobs:
  audit:
    runs-on: macOS-latest
    steps:
      - uses: actions/checkout@v4
      - run: |
          cd meme_tracker
          ./security_check.sh
          git add config/SECURITY.log
          git commit -m "月度安全审计 $(date +%Y-%m-%d)"
