name: Monthly Security Audit
on:
  schedule:
    - cron: "0 0 1 * *"  # 每月1日午夜运行
  workflow_dispatch:     # 允许手动触发

jobs:
  security-scan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
          
      - name: Install dependencies
        run: |
          pip install safety bandit
          
      - name: Run security checks
        run: |
          echo "=== Dependency Vulnerability Scan ==="
          safety check --full-report
          
          echo "\n=== Code Security Analysis ==="
          bandit -r meme_tracker/ -f html -o security_report.html
          
      - name: Upload report
        uses: actions/upload-artifact@v3
        with:
          name: security-audit-report
          path: |
            security_report.html